-- 添加新字段
ALTER TABLE users 
ADD COLUMN nickname VARCHAR(50) NULL COMMENT '用户昵称，可为空，最大长度50',
ADD COLUMN gender TINYINT NULL COMMENT '性别：0-未知，1-男，2-女',
ADD COLUMN birthday DATE NULL COMMENT '生日',
ADD COLUMN bio TEXT NULL COMMENT '个人简介',
ADD COLUMN last_login_time DATETIME NULL COMMENT '最后登录时间',
ADD COLUMN last_login_ip VARCHAR(50) NULL COMMENT '最后登录IP';

-- 确保所有字段可空
ALTER TABLE users 
MODIFY COLUMN nickname VARCHAR(50) NULL COMMENT '用户昵称，可为空，最大长度50',
MODIFY COLUMN gender TINYINT NULL COMMENT '性别：0-未知，1-男，2-女',
MODIFY COLUMN birthday DATE NULL COMMENT '生日',
MODIFY COLUMN bio TEXT NULL COMMENT '个人简介',
MODIFY COLUMN last_login_time DATETIME NULL COMMENT '最后登录时间',
MODIFY COLUMN last_login_ip VARCHAR(50) NULL COMMENT '最后登录IP'; 